# Generated by Django 3.2 on 2021-07-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='account',
            name='other_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='first name'),
        ),
    ]
