# Generated by Django 3.2 on 2021-07-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210703_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='other_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='other name(s)'),
        ),
    ]
