# Generated by Django 3.2 on 2021-07-05 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0002_articles_myself'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myself',
            options={'ordering': ['-date_created']},
        ),
    ]
