# Generated by Django 3.2 on 2021-07-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0003_alter_myself_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myself',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
