# Generated by Django 3.2 on 2021-07-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0004_alter_myself_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myself',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
