# Generated by Django 3.2 on 2021-07-06 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0006_alter_myself_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('course_desc', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField()),
            ],
            options={
                'ordering': ['date_added'],
            },
        ),
        migrations.AlterModelOptions(
            name='myself',
            options={'ordering': ['date_created']},
        ),
        migrations.CreateModel(
            name='BackEndCourse',
            fields=[
                ('courseparent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='about_me.courseparent')),
            ],
            bases=('about_me.courseparent',),
        ),
        migrations.CreateModel(
            name='FrontEndCourse',
            fields=[
                ('courseparent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='about_me.courseparent')),
            ],
            bases=('about_me.courseparent',),
        ),
    ]
