# Generated by Django 3.2 on 2021-07-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0007_auto_20210706_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseparent',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
