# Generated by Django 3.2 on 2021-07-06 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0008_alter_courseparent_date_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseparent',
            options={'ordering': ['date_updated']},
        ),
    ]
