# Generated by Django 3.2 on 2021-07-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0012_usefullinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseparent',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
