# Generated by Django 3.2 on 2021-07-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0013_courseparent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcontact',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='phonecontact',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
