# Generated by Django 3.2 on 2021-07-07 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0014_auto_20210706_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontEndTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(blank=True, max_length=200, null=True)),
                ('topic_desc', models.TextField(blank=True, null=True)),
                ('topic_video', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about_me.frontendcourse')),
            ],
        ),
    ]
