# Generated by Django 3.2 on 2021-07-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0015_frontendtopics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontendtopics',
            name='topic_video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
