# Generated by Django 3.2 on 2022-07-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0018_alter_emailcontact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
