# Generated by Django 3.2 on 2022-06-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220607_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=250), max_length=250, unique_for_date='publish'),
        ),
    ]
