# Generated by Django 3.2 on 2022-06-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('politics', 'politics'), ('Techs', 'Techs'), ('News', 'News')], default='News', max_length=20),
        ),
    ]
