# Generated by Django 3.2 on 2021-08-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_viewable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-updated_on']},
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
